name: clip4cad
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.1
      - attrs==25.4.0
      - black==26.1.0
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clip4cad==0.1.0
      - colorama==0.4.6
      - comm==0.2.3
      - configargparse==1.7.1
      - dash==3.3.0
      - decorator==5.2.1
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - faiss-cpu==1.13.2
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flask==3.1.2
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - h5py==3.15.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.6
      - omegaconf==2.3.0
      - open3d==0.19.0
      - packaging==25.0
      - parso==0.8.5
      - pathspec==1.0.3
      - pillow==12.0.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.4
      - psutil==7.2.1
      - pure-eval==0.2.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pytest==9.0.2
      - pytokens==0.3.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.49.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.6
      - trimesh==4.11.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - wandb==0.24.0
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: C:\Users\User\anaconda3\envs\clip4cad
